# Generated by Django 4.2.11 on 2024-05-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minidrive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
