# Generated by Django 3.2.3 on 2024-02-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pan',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pan',
            name='nombre',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='pan',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
